name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天同步一次
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false # 禁止使用默认的GitHub Token
          fetch-depth: 0 # 完整克隆所有历史记录

      - name: Configure the upstream repo
        run: git remote add upstream https://github.com/langgenius/dify.git

      - name: Fetch all branches from the upstream repo
        run: git fetch upstream

      - name: Sync with the upstream repo
        run: git merge upstream/main

      - name: Push changes to the forked repo
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
